# Generated by Django 5.1.4 on 2026-04-21 18:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=50)),
                ('lang', models.CharField(default='tr', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='GTFSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.CharField(choices=[('iett', 'İETT'), ('public', 'Genel Toplu Ulaşım')], max_length=20, unique=True)),
                ('zip_hash', models.CharField(help_text='SHA-256 of source ZIP', max_length=64)),
                ('imported_at', models.DateTimeField()),
                ('routes_count', models.PositiveIntegerField(default=0)),
                ('stops_count', models.PositiveIntegerField(default=0)),
                ('trips_count', models.PositiveIntegerField(default=0)),
                ('stop_times_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'GTFS Feed',
                'verbose_name_plural': 'GTFS Feeds',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shape_id', models.CharField(max_length=50, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_type', models.IntegerField(choices=[(0, 'Stop'), (1, 'Station'), (2, 'Entrance')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_id', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=200)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram'), (1, 'Subway'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (6, 'Aerial'), (7, 'Funicular')])),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gtfs.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_id', models.CharField(max_length=100, unique=True)),
                ('headsign', models.CharField(max_length=200)),
                ('direction_id', models.IntegerField(default=0)),
                ('service_id', models.CharField(db_index=True, max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='gtfs.route')),
                ('shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='gtfs.shape')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_time', models.DurationField()),
                ('departure_time', models.DurationField()),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
                'indexes': [models.Index(fields=['trip', 'stop_sequence'], name='st_trip_seq_idx')],
            },
        ),
    ]
