# Generated by Django 5.1.4 on 2026-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'gtfs_calendar',
                'indexes': [models.Index(fields=['monday'], name='gtfs_calend_monday_64c137_idx'), models.Index(fields=['tuesday'], name='gtfs_calend_tuesday_f72131_idx'), models.Index(fields=['wednesday'], name='gtfs_calend_wednesd_22e5cc_idx'), models.Index(fields=['thursday'], name='gtfs_calend_thursda_5e39ee_idx'), models.Index(fields=['friday'], name='gtfs_calend_friday_838879_idx'), models.Index(fields=['saturday'], name='gtfs_calend_saturda_c1fcc8_idx'), models.Index(fields=['sunday'], name='gtfs_calend_sunday_21eb32_idx')],
            },
        ),
    ]
